### PR TITLE
[PF-364] Add v2 button

### PR DESCRIPTION
**Pull request by manuzope**
The main page still looks the same.

Other pages look like this:
screen shot 2016-05-13 at 10 08 39 am

Reviewers: @steverice @billkauf @brhou @shabemdadi @znli 
Design: Jeff

### CODE REVIEW

**Comment by brhou** [comment]
👍

**Comment by brhou** [comment]
Maybe make the button a little more narrow?

**Comment by billkauf** [comment]
👍

**Comment by steverice** [comment]
LGTM!

**Pull request merged**
