### PR TITLE
Updated "Service key" to "Integration key"...

### PR DESCRIPTION
**Pull request by mdcollins05**
Cause that's what it's called now!

### CODE REVIEW

**Comment by steverice** [comment]
True, but we still refer to it as the "service_key" in the v1 and events APIs. Perhaps we should make a note of that nuance here.

**Comment by mdcollins05** [comment]
That's fair. What messaging would you suggest instead?

**Comment by steverice** [comment]
@mdcollins05 we have [quite a nice support guide](https://support.pagerduty.com/hc/en-us/articles/202830340-Creating-a-Generic-API-Integration) with goodies like screenshots that does a much better job of walking through the integration setup process. I've proposed linking to that instead in #64.

**Comment by steverice** [comment]
Closing in favor of #64, which has number of other related updates.

**Pull request closed without merging**
