### PR TITLE
Tidy HTML

### PR DESCRIPTION
**Pull request by steverice**
Use HTML tidy to clean up and reformat source HTML.
Also fixes some bugs that were exposed or made more obvious by the tidying.

Correctness verified by some basic `diff`ing of the resulting `public` directories built between this and `master` as well as visual inspection in the development environment.

The resulting diff ain't pretty to look at no matter how you slice it, but I'd recommend [a unified diff with whitespace ignored](https://github.com/PagerDuty/devdocs/pull/8/files?diff=unified&w=1).

Dirty details:
The tricky bit is that HTML Tidy doesn't know about the YAML in these files, so it will clobber it and break the Jekyll configuration.
To avoid this, we take a multi-step approach:

- `find source/documentation/ -type f -name "*.html" -exec perl -0777 -pi -e 's/---.*---\n/\n/igs' {} \;`
  - strip all YAML out of these files and replace it with a newline
- `git commit -a`
  - commit the result
- `git format-patch -U0 HEAD^ --stdout > /path/to/patch.patch`
  - create a patch that represents the change we just made (removing YAML). Crucially, include 0 lines of context in the diff as the lines around the YAML will change and this will cause merge conflicts with any context we have.
- `find source/documentation/ -type f -name "*.html" -exec tidy -q -config .tidy-config {} \;`
  - run HTML Tidy on all of the HTML files. Since no YAML exists in these files any longer, all we process is the HTML.
- `git commit -a`
  - commit the result
- `patch -R -p1 < /path/to/patch.patch`
  - apply the patch we created earlier in reverse, effectively re-adding all of the YAML
- `git reset --soft HEAD~2`
  - rewind two commits so we're left with the final result and not the intermediate commits
- `git commit -a`
  - commit the final result (this commit)

### CODE REVIEW

**Comment by eurica** [comment]
I skimmed the code changes, looks sound.  And Steve's methodology looks good.  If the output looks good, I'm happy to call this CR-ed.

Ship it.

**Comment by afolson** [comment]
I found a line that was eaten during the tidy process: https://github.com/PagerDuty/devdocs/pull/8/files?diff=unified&w=1#diff-6d934eb4f6323935bb0f4dd393e65788L22

**Comment by steverice** [comment]
@afolson I moved it out of the table: https://github.com/PagerDuty/devdocs/pull/8/files?diff=unified&w=1#diff-6d934eb4f6323935bb0f4dd393e65788R18

**Comment by steverice** [comment]
I re-did the tidy [with `UTF-8` specified as the file encoding](https://github.com/PagerDuty/devdocs/pull/8/files#diff-fcd6708c4771407b503751e471fa0ea6R7). Without this Tidy had converted a number of UTF-8 characters into their `&#0123;`-type equivalents, which are impossible to read and unnecessary when Jekyll handles the UTF-8 stuff without issue.

**Pull request merged**
